### ISSUE TITLE
Request for ASPLOS 2024 Presentation Slides

### ISSUE THREAD

**Issue by Light-of-Hers** [akothen/Hydride#6]
Hi Akash Kothari,

I thoroughly enjoyed your paper "Hydride: A Retargetable and Extensible Synthesis-based Compiler for Modern Hardware Architectures" presented at ASPLOS 2024. I am currently engaged in a project that aligns closely with your research, and I believe that reviewing your presentation slides would provide valuable insights and context.

Would it be possible for you to share the slides from your ASPLOS 2024 presentation? I would greatly appreciate it if you could make them available.

Thank you very much for your time and consideration.

**Comment by akothen** [comment]
Hi, can you please share your email? I will be happy to share my slides via email. Thanks.

**Comment by Light-of-Hers** [comment]
> Hi, can you please share your email? I will be happy to share my slides via email. Thanks.

Thank you for your prompt response. My e-mail is crz@pku.edu.cn .
