### ISSUE TITLE
Synthesize to AVX instead of AVX512 in x86 mode

### ISSUE THREAD

**Issue by seungbinsong** [akothen/Hydride#8]
Hi Akash Kothari,

I really enjoyed your paper Hydride in ASPLOS'24, and I am working on running a benchmark in `benchmarks/x86/halide/add`. I set up x86 mode with `source setup.sh x86`, but I find that the synthesized assembly (add.a) has `vpbroadcastw` instruction which is in AVX512 but not in AVX. Unfortunately, my machine is Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz and it only supports AVX. 

Is there any configuration to change the target architecture to AVX instead of AVX512 in x86 mode?

Thanks.

**Comment by akothen** [comment]
Let me discuss this internally and get back to you.

**Comment by akothen** [comment]
Can you please try using this: https://github.com/akothen/Hydride/blob/main/code-synthesizer/dsl-ir/utils/GetLegalInstructions.py to get legal instructions for your machine?

**Comment by akothen** [comment]
Closing this issue for now. Please open another if you continue to face issues.
